### ISSUE TITLE
mungers/flakesync tests take too long

### ISSUE THREAD

**Issue by mwielgus** [kubernetes/contrib#1118]
```
SIGQUIT: quit
PC=0x45aea1 m=0
goroutine 0 [idle]:
runtime.futex(0x66d0a8, 0x0, 0x0, 0x0, 0x0, 0x66c9f0, 0x0, 0x0, 0x40da24, 0x66d0a8, ...)
	/home/travis/.gimme/versions/go1.6.linux.amd64/src/runtime/sys_linux_amd64.s:302 +0x21
runtime.futexsleep(0x66d0a8, 0x0, 0xffffffffffffffff)
	/home/travis/.gimme/versions/go1.6.linux.amd64/src/runtime/os1_linux.go:40 +0x53
runtime.notesleep(0x66d0a8)
	/home/travis/.gimme/versions/go1.6.linux.amd64/src/runtime/lock_futex.go:145 +0xa4
runtime.stopm()
	/home/travis/.gimme/versions/go1.6.linux.amd64/src/runtime/proc.go:1535 +0x10b
runtime.findrunnable(0xc820022000, 0x0)
	/home/travis/.gimme/versions/go1.6.linux.amd64/src/runtime/proc.go:1973 +0x739
runtime.schedule()
	/home/travis/.gimme/versions/go1.6.linux.amd64/src/runtime/proc.go:2072 +0x24f
runtime.park_m(0xc820000a80)
	/home/travis/.gimme/versions/go1.6.linux.amd64/src/runtime/proc.go:2137 +0x18b
runtime.mcall(0x7fff1e4f67f0)
	/home/travis/.gimme/versions/go1.6.linux.amd64/src/runtime/asm_amd64.s:233 +0x5b
goroutine 1 [chan receive, 9 minutes]:
testing.RunTests(0x5d8160, 0x666a20, 0x2, 0x2, 0xc820076001)
	/home/travis/.gimme/versions/go1.6.linux.amd64/src/testing/testing.go:583 +0x8d2
testing.(*M).Run(0xc820049f08, 0xc8200760e8)
	/home/travis/.gimme/versions/go1.6.linux.amd64/src/testing/testing.go:515 +0x81
main.main()
	k8s.io/contrib/mungegithub/mungers/flakesync/_test/_testmain.go:56 +0x117
goroutine 5 [runnable]:
type..eq.k8s.io/contrib/mungegithub/mungers/flakesync.key(0xc820046e28, 0xc820074260, 0x4244399d13c7d175)
	/home/travis/gopath/src/k8s.io/contrib/mungegithub/mungers/flakesync/cache.go:1
k8s.io/contrib/mungegithub/mungers/flakesync.(*Cache).lookup(0xc8200145a0, 0x592898, 0x3, 0x6, 0x0, 0x0)
	/home/travis/gopath/src/k8s.io/contrib/mungegithub/mungers/flakesync/cache.go:132 +0xce
k8s.io/contrib/mungegithub/mungers/flakesync.(*Cache).Get(0xc8200145a0, 0x592898, 0x3, 0x6, 0xc82001c3c0, 0x0, 0x0)
	/home/travis/gopath/src/k8s.io/contrib/mungegithub/mungers/flakesync/cache.go:122 +0x4f
k8s.io/contrib/mungegithub/mungers/flakesync.TestBasic(0xc82001e120)
	/home/travis/gopath/src/k8s.io/contrib/mungegithub/mungers/flakesync/cache_test.go:47 +0x467
testing.tRunner(0xc82001e120, 0x666a20)
	/home/travis/.gimme/versions/go1.6.linux.amd64/src/testing/testing.go:473 +0x98
created by testing.RunTests
	/home/travis/.gimme/versions/go1.6.linux.amd64/src/testing/testing.go:582 +0x892
rax    0xca
rbx    0x0
rcx    0xffffffffffffffff
rdx    0x0
rdi    0x66d0a8
rsi    0x0
rbp    0x1
rsp    0x7fff1e4f6650
r8     0x0
r9     0x0
r10    0x0
r11    0x286
r12    0x1740
r13    0x20
r14    0x1
r15    0x8
rip    0x45aea1
rflags 0x286
cs     0x33
fs     0x0
gs     0x0
*** Test killed with quit: ran too long (10m0s).
FAIL	k8s.io/contrib/mungegithub/mungers/flakesync	600.065s
```

**Comment by lavalamp** [comment]
Apparently not fixed by #1126 :(
