### ISSUE TITLE
Cluster-autoscaler: panic in GetMigForInstance in gce e2e tests

### ISSUE THREAD

**Issue by mwielgus** [kubernetes/contrib#1214]
cc: @piosz @jszczepkowski @fgrzadkowski 
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x519518]

goroutine 1 [running]:
panic(0x1b54d00, 0xc820016070)
	/usr/local/google/home/mwielgus/.gvm/gos/go1.6.2/src/runtime/panic.go:481 +0x3e6
k8s.io/contrib/cluster-autoscaler/utils/gce.(*GceManager).GetMigForInstance(0x0, 0xc82053c900, 0x0, 0x0, 0x0)
	/usr/local/google/home/mwielgus/go/src/k8s.io/contrib/cluster-autoscaler/utils/gce/gce.go:162 +0x4c8
main.CheckMigsAndNodes(0xc8205658e0, 0x3, 0x4, 0x0, 0x0, 0x0)
	/usr/local/google/home/mwielgus/go/src/k8s.io/contrib/cluster-autoscaler/utils.go:240 +0x222
main.main()
	/usr/local/google/home/mwielgus/go/src/k8s.io/contrib/cluster-autoscaler/cluster_autoscaler.go:135 +0xdb2
```

**Comment by piosz** [comment]
fixed in #1215
