### ISSUE TITLE
Attempt to use ansible/vagrant fails: AttributeError: 'module' object has no attribute 'selinux_snapperd_contexts_path'

### ISSUE THREAD

**Issue by mjbright** [kubernetes/contrib#1584]
I'm trying to use https://github.com/kubernetes/contrib/blob/master/ansible/vagrant/Vagrantfile
I commented out requires:
```
    #require 'vagrant-openstack-provider'
    #require 'vagrant-aws'
```
Attempts to use "vagrant up" or "vagrant provision" finish with an selinux error - see below.

**Note:** I am running VirtualBox 5.1.4r110228, Vagrant 1.8.1 on Fedora 24.

> vagrant provision
==> kube-node-2: Running provisioner: ansible...
    kube-node-2: Running ansible-playbook...
ERROR! Unexpected Exception: 'module' object has no attribute 'selinux_snapperd_contexts_path'
the full traceback was:

Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 79, in <module>
    mycli = getattr(__import__("ansible.cli.%s" % sub, fromlist=[myclass]), myclass)
  File "/usr/lib/python2.7/site-packages/ansible/cli/playbook.py", line 30, in <module>
    from ansible.executor.playbook_executor import PlaybookExecutor
  File "/usr/lib/python2.7/site-packages/ansible/executor/playbook_executor.py", line 27, in <module>
    from ansible.executor.task_queue_manager import TaskQueueManager
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_queue_manager.py", line 28, in <module>
    from ansible.executor.play_iterator import PlayIterator
  File "/usr/lib/python2.7/site-packages/ansible/executor/play_iterator.py", line 29, in <module>
    from ansible.playbook.block import Block
  File "/usr/lib/python2.7/site-packages/ansible/playbook/__init__.py", line 25, in <module>
    from ansible.playbook.play import Play
  File "/usr/lib/python2.7/site-packages/ansible/playbook/play.py", line 27, in <module>
    from ansible.playbook.base import Base
  File "/usr/lib/python2.7/site-packages/ansible/playbook/base.py", line 35, in <module>
    from ansible.parsing.dataloader import DataLoader
  File "/usr/lib/python2.7/site-packages/ansible/parsing/dataloader.py", line 35, in <module>
    from ansible.parsing.yaml.loader import AnsibleLoader
  File "/usr/lib/python2.7/site-packages/ansible/parsing/yaml/loader.py", line 30, in <module>
    from ansible.parsing.yaml.constructor import AnsibleConstructor
  File "/usr/lib/python2.7/site-packages/ansible/parsing/yaml/constructor.py", line 25, in <module>
    from ansible.vars.unsafe_proxy import wrap_var
  File "/usr/lib/python2.7/site-packages/ansible/vars/__init__.py", line 39, in <module>
    from ansible.inventory.host import Host
  File "/usr/lib/python2.7/site-packages/ansible/inventory/__init__.py", line 33, in <module>
    from ansible.inventory.dir import InventoryDirectory, get_file_parser
  File "/usr/lib/python2.7/site-packages/ansible/inventory/dir.py", line 32, in <module>
    from ansible.inventory.script import InventoryScript
  File "/usr/lib/python2.7/site-packages/ansible/inventory/script.py", line 33, in <module>
    from ansible.module_utils.basic import json_dict_bytes_to_unicode
  File "/usr/lib/python2.7/site-packages/ansible/module_utils/basic.py", line 147, in <module>
    import selinux
  File "/usr/lib64/python2.7/site-packages/selinux/__init__.py", line 1441, in <module>
    selinux_snapperd_contexts_path = _selinux.selinux_snapperd_contexts_path
AttributeError: 'module' object has no attribute 'selinux_snapperd_contexts_path'
Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

**Comment by mjbright** [comment]
Just realized that this is a pure ansible(/my Fedora 24) issue as
```
ansible --version
```
produces the same error.

**Comment by mjbright** [comment]
Not at all a kubernetes/config problem, but a problem with my Fedora24/ansible

**Comment by yuripourre** [comment]
I have the same problem, how do you solved it?

**Comment by mjbright** [comment]
Hi, yes I solved this problem.

It turned out I had 2 copies of some Python selinux policy module.
I believe that the older copy was coming from a Docker installation made from getdocker.com script.

As I posted here:
    https://bugzilla.redhat.com/show_bug.cgi?id=1364703

This is how I fixed the problem (after uninstalling Docker and reinstalling from official F24 repo):

> I was able to compare with another F24 installation which didn't have this problem.  comparing the output of "strace ansible --version" showed me that the problematic install had an extra file:
>     /usr/lib64/python2.7/site-packages/selinux/_selinux.so
> 
> This was due to me having 2 libselinux-python rpms installed
> 
>     > rpm -qa | grep libselinux-python
>     libselinux-python-2.5-9.fc24.x86_64
>     libselinux-python-2.5-3.fc24.x86_64
> 
> Removing the older package
>     dnf remove libselinux-python-2.5-3.fc24.x86_64
> 
> solved my problem.
>

**Comment by yuripourre** [comment]
Thank you, it works!
