### ISSUE TITLE
Problems using zookeeper petset with latest stable version

### ISSUE THREAD

**Issue by mkobetic** [kubernetes/contrib#1877]
I'm using the petset yaml pretty much as is, just minimal tweaks to bump it down to the latest stable (2.4.9 atm), which should be something like this IIUC:
```
@@ -36,7 +43,7 @@
                 "name": "install",
                 "image": "gcr.io/google_containers/zookeeper-install:0.1",
                 "imagePullPolicy": "Always",
-                "args": ["--version=3.5.0-alpha", "--install-into=/opt", "--work-dir=/work-dir"],
+                "args": ["--version=3.4.9", "--install-into=/opt", "--work-dir=/work-dir"],
                 "volumeMounts": [
                     {
                         "name": "opt",
@@ -52,7 +59,7 @@
                 "name": "bootstrap",
                 "image": "java:openjdk-8-jre",
                 "command": ["/work-dir/peer-finder"],
-                "args": ["-on-start=\"/work-dir/on-start.sh\"", "-service=zk"],
+                "args": ["-on-start=\"/work-dir/on-change.sh\"", "-service=zk"],
                 "env": [
                   {
                       "name": "POD_NAMESPACE",
```
Just running this modified yaml through `kubectl create`, starts the first pet, then moves on to the second and stops. Looking at the logs it seems that the first pet just decides to run in standalone mode and then the second fails trying to connect to the election port.

Here's the start of the zoo-0 log (note the WARN line about the standalone mode):
```
ZooKeeper JMX enabled by default
Using config: /opt/zookeeper/bin/../conf/zoo.cfg
2016-10-13 17:26:24,020 [myid:] - INFO  [main:QuorumPeerConfig@124] - Reading configuration from: /opt/zookeeper/bin/../conf/zoo.cfg
2016-10-13 17:26:24,034 [myid:] - INFO  [main:QuorumPeer$QuorumServer@149] - Resolved hostname: zoo-0.zk.default.svc.cluster.local to address: zoo-0.zk.default.svc.cluster.local/10.0.2.5
2016-10-13 17:26:24,034 [myid:] - ERROR [main:QuorumPeerConfig@301] - Invalid configuration, only one server specified (ignoring)
2016-10-13 17:26:24,036 [myid:] - INFO  [main:DatadirCleanupManager@78] - autopurge.snapRetainCount set to 3
2016-10-13 17:26:24,036 [myid:] - INFO  [main:DatadirCleanupManager@79] - autopurge.purgeInterval set to 0
2016-10-13 17:26:24,036 [myid:] - INFO  [main:DatadirCleanupManager@101] - Purge task is not scheduled.
2016-10-13 17:26:24,036 [myid:] - WARN  [main:QuorumPeerMain@113] - Either no config or no quorum defined in config, running  in standalone mode
2016-10-13 17:26:24,047 [myid:] - INFO  [main:QuorumPeerConfig@124] - Reading configuration from: /opt/zookeeper/bin/../conf/zoo.cfg
2016-10-13 17:26:24,048 [myid:] - INFO  [main:QuorumPeer$QuorumServer@149] - Resolved hostname: zoo-0.zk.default.svc.cluster.local to address: zoo-0.zk.default.svc.cluster.local/10.0.2.5
2016-10-13 17:26:24,048 [myid:] - ERROR [main:QuorumPeerConfig@301] - Invalid configuration, only one server specified (ignoring)
2016-10-13 17:26:24,048 [myid:] - INFO  [main:ZooKeeperServerMain@96] - Starting server
2016-10-13 17:26:24,054 [myid:] - INFO  [main:Environment@100] - Server environment:zookeeper.version=3.4.9-1757313, built on 08/23/2016 06:50 GMT
2016-10-13 17:26:24,054 [myid:] - INFO  [main:Environment@100] - Server environment:host.name=zoo-0.zk.default.svc.cluster.local
2016-10-13 17:26:24,054 [myid:] - INFO  [main:Environment@100] - Server environment:java.version=1.8.0_102
2016-10-13 17:26:24,054 [myid:] - INFO  [main:Environment@100] - Server environment:java.vendor=Oracle Corporation
2016-10-13 17:26:24,054 [myid:] - INFO  [main:Environment@100] - Server environment:java.home=/usr/lib/jvm/java-8-openjdk-amd64/jre
2016-10-13 17:26:24,056 [myid:] - INFO  [main:Environment@100] - Server environment:java.class.path=/opt/zookeeper/bin/../build/classes:/opt/zookeeper/bin/../build/lib/*.jar:/opt/zookeeper/bin/../lib/slf4j-log4j12-1.6.1.jar:/opt/zookeeper/bin/../lib/slf4j-api-1.6.1.jar:/opt/zookeeper/bin/../lib/netty-3.10.5.Final.jar:/opt/zookeeper/bin/../lib/log4j-1.2.16.jar:/opt/zookeeper/bin/../lib/jline-0.9.94.jar:/opt/zookeeper/bin/../zookeeper-3.4.9.jar:/opt/zookeeper/bin/../src/java/lib/*.jar:/opt/zookeeper/bin/../conf:
2016-10-13 17:26:24,056 [myid:] - INFO  [main:Environment@100] - Server environment:java.library.path=/usr/java/packages/lib/amd64:/usr/lib/x86_64-linux-gnu/jni:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/usr/lib/jni:/lib:/usr/lib
2016-10-13 17:26:24,056 [myid:] - INFO  [main:Environment@100] - Server environment:java.io.tmpdir=/tmp
2016-10-13 17:26:24,056 [myid:] - INFO  [main:Environment@100] - Server environment:java.compiler=<NA>
2016-10-13 17:26:24,056 [myid:] - INFO  [main:Environment@100] - Server environment:os.name=Linux
2016-10-13 17:26:24,056 [myid:] - INFO  [main:Environment@100] - Server environment:os.arch=amd64
2016-10-13 17:26:24,056 [myid:] - INFO  [main:Environment@100] - Server environment:os.version=4.4.14+
2016-10-13 17:26:24,056 [myid:] - INFO  [main:Environment@100] - Server environment:user.name=root
2016-10-13 17:26:24,056 [myid:] - INFO  [main:Environment@100] - Server environment:user.home=/root
2016-10-13 17:26:24,056 [myid:] - INFO  [main:Environment@100] - Server environment:user.dir=/
2016-10-13 17:26:24,063 [myid:] - INFO  [main:ZooKeeperServer@815] - tickTime set to 2000
2016-10-13 17:26:24,063 [myid:] - INFO  [main:ZooKeeperServer@824] - minSessionTimeout set to -1
2016-10-13 17:26:24,063 [myid:] - INFO  [main:ZooKeeperServer@833] - maxSessionTimeout set to -1
2016-10-13 17:26:24,072 [myid:] - INFO  [main:NIOServerCnxnFactory@89] - binding to port 0.0.0.0/0.0.0.0:2181
```
The second pet set starts ok but gets ECONREFUSED when trying to reach the election port of the first pet
```
ZooKeeper JMX enabled by default
Using config: /opt/zookeeper/bin/../conf/zoo.cfg
2016-10-13 17:27:20,983 [myid:] - INFO  [main:QuorumPeerConfig@124] - Reading configuration from: /opt/zookeeper/bin/../conf/zoo.cfg
2016-10-13 17:27:21,001 [myid:] - INFO  [main:QuorumPeer$QuorumServer@149] - Resolved hostname: zoo-0.zk.default.svc.cluster.local to address: zoo-0.zk.default.svc.cluster.local/10.0.2.5
2016-10-13 17:27:21,001 [myid:] - INFO  [main:QuorumPeer$QuorumServer@149] - Resolved hostname: zoo-1.zk.default.svc.cluster.local to address: zoo-1.zk.default.svc.cluster.local/10.0.0.6
2016-10-13 17:27:21,002 [myid:] - WARN  [main:QuorumPeerConfig@305] - No server failure will be tolerated. You need at least 3 servers.
2016-10-13 17:27:21,002 [myid:] - INFO  [main:QuorumPeerConfig@352] - Defaulting to majority quorums
2016-10-13 17:27:21,005 [myid:2] - INFO  [main:DatadirCleanupManager@78] - autopurge.snapRetainCount set to 3
2016-10-13 17:27:21,006 [myid:2] - INFO  [main:DatadirCleanupManager@79] - autopurge.purgeInterval set to 0
2016-10-13 17:27:21,006 [myid:2] - INFO  [main:DatadirCleanupManager@101] - Purge task is not scheduled.
2016-10-13 17:27:21,016 [myid:2] - INFO  [main:QuorumPeerMain@127] - Starting quorum peer
2016-10-13 17:27:21,025 [myid:2] - INFO  [main:NIOServerCnxnFactory@89] - binding to port 0.0.0.0/0.0.0.0:2181
2016-10-13 17:27:21,031 [myid:2] - INFO  [main:QuorumPeer@1019] - tickTime set to 2000
2016-10-13 17:27:21,032 [myid:2] - INFO  [main:QuorumPeer@1039] - minSessionTimeout set to -1
2016-10-13 17:27:21,032 [myid:2] - INFO  [main:QuorumPeer@1050] - maxSessionTimeout set to -1
2016-10-13 17:27:21,032 [myid:2] - INFO  [main:QuorumPeer@1065] - initLimit set to 10
2016-10-13 17:27:21,047 [myid:2] - INFO  [ListenerThread:QuorumCnxManager$Listener@534] - My election bind port: zoo-1.zk.default.svc.cluster.local/10.0.0.6:3888
2016-10-13 17:27:21,054 [myid:2] - INFO  [QuorumPeer[myid=2]/0:0:0:0:0:0:0:0:2181:QuorumPeer@774] - LOOKING
2016-10-13 17:27:21,056 [myid:2] - INFO  [QuorumPeer[myid=2]/0:0:0:0:0:0:0:0:2181:FastLeaderElection@818] - New election. My id =  2, proposed zxid=0x0
2016-10-13 17:27:21,061 [myid:2] - WARN  [WorkerSender[myid=2]:QuorumCnxManager@400] - Cannot open channel to 1 at election address zoo-0.zk.default.svc.cluster.local/10.0.2.5:3888
java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.zookeeper.server.quorum.QuorumCnxManager.connectOne(QuorumCnxManager.java:381)
	at org.apache.zookeeper.server.quorum.QuorumCnxManager.toSend(QuorumCnxManager.java:354)
	at org.apache.zookeeper.server.quorum.FastLeaderElection$Messenger$WorkerSender.process(FastLeaderElection.java:452)
	at org.apache.zookeeper.server.quorum.FastLeaderElection$Messenger$WorkerSender.run(FastLeaderElection.java:433)
	at java.lang.Thread.run(Thread.java:745)
```

@bprashanth, did this work before? Hopefully there's a way to force the first pet out of standalone mode despite being lonely?

/cc @ibawt

**Comment by mkobetic** [comment]
Never mind, I figured out how to use the peer-finder correctly for the pre 3.5.0 zookeeper, i.e. don't use it as an init-container but instead as the zk container itself, so mostly just move the bootstrap init container bits into the main zk container definition:
```
@@ -90,9 +66,16 @@
         - containerPort: 3888
           name: leader-election
         command:
-        - /opt/zookeeper/bin/zkServer.sh
+        - /work-dir/peer-finder
         args:
-        - start-foreground
+        - -on-change="/work-dir/on-change.sh"
+        - -service=zk
+        env:
+        - name: POD_NAMESPACE
+          valueFrom:
+            fieldRef:
+              apiVersion: v1
+              fieldPath: metadata.namespace
         readinessProbe:
           exec:
             command:
@@ -106,6 +89,8 @@
           mountPath: /tmp/zookeeper
         - name: opt
           mountPath: /opt/
+        - name: workdir
+          mountPath: /work-dir
       volumes:
       - name: opt
         emptyDir: {}
```
with these changes the petset seems to scale up to three nodes just fine.

Sorry about the noise.

**Comment by bprashanth** [comment]
@mkobetic for on-change it needs to run in the app container. Current zookeeper example only uses on-start, which can run completely in init such that zookeeper itself is pid1. 
https://github.com/kubernetes/contrib/blob/master/pets/zookeeper/zookeeper.yaml#L55

**Comment by mkobetic** [comment]
@bprashanth, yup I realized that eventually, I posted the changes I made to the petset yaml above; with those the pet set spun up and has been running ever since. Thanks!
