### ISSUE TITLE
Nginx Ingress controller crash issue (golang panic)

### ISSUE THREAD

**Issue by tjliupeng** [kubernetes/contrib#2139]
Hi,

In one of my colleague test K8s env, the nginx ingress controller can't start. The trace is as follow:
```
[root@petercentos7 output]# kubectl logs nginx-ingress-controller-26hys
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x40922c]

goroutine 101 [running]:
panic(0x19a2800, 0xc420014030)
               /usr/local/go/src/runtime/panic.go:500 +0x1a1
main.(*loadBalancerController).getUpstreamServers(0xc420196a00, 0x1b6f3ff, 0x2, 0x1b8bd89, 0x1b, 0x1000101, 0x1b6f77a, 0x3, 0x0, 0x1b725c8, ...)
               /home/itsma/service-lb/nginx-ingress-controller/src/k8s.io/contrib/ingress/controllers/nginx/controller.go:746 +0x1cdc
main.(*loadBalancerController).sync(0xc420196a00, 0xc420012d60, 0x16, 0xc420153ea0, 0xc420153e00)
               /home/itsma/service-lb/nginx-ingress-controller/src/k8s.io/contrib/ingress/controllers/nginx/controller.go:466 +0x176
main.(*loadBalancerController).(main.sync)-fm(0xc420012d60, 0x16, 0xc420153ea0, 0xc42004fe00)
               /home/itsma/service-lb/nginx-ingress-controller/src/k8s.io/contrib/ingress/controllers/nginx/controller.go:161 +0x3e
main.(*taskQueue).worker(0xc4203a26a0)
               /home/itsma/service-lb/nginx-ingress-controller/src/k8s.io/contrib/ingress/controllers/nginx/utils.go:90 +0x152
main.(*taskQueue).(main.worker)-fm()
               /home/itsma/service-lb/nginx-ingress-controller/src/k8s.io/contrib/ingress/controllers/nginx/utils.go:64 +0x2a
k8s.io/contrib/ingress/vendor/k8s.io/kubernetes/pkg/util/wait.JitterUntil.func1(0xc42081ff48)
               /home/itsma/service-lb/nginx-ingress-controller/src/k8s.io/contrib/ingress/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:84 +0x19
k8s.io/contrib/ingress/vendor/k8s.io/kubernetes/pkg/util/wait.JitterUntil(0xc42081ff48, 0x3b9aca00, 0x0, 0x1, 0xc4203c5da0)
               /home/itsma/service-lb/nginx-ingress-controller/src/k8s.io/contrib/ingress/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:85 +0xad
k8s.io/contrib/ingress/vendor/k8s.io/kubernetes/pkg/util/wait.Until(0xc42081ff48, 0x3b9aca00, 0xc4203c5da0)
               /home/itsma/service-lb/nginx-ingress-controller/src/k8s.io/contrib/ingress/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:47 +0x4d
main.(*taskQueue).run(0xc4203a26a0, 0x3b9aca00, 0xc4203c5da0)
               /home/itsma/service-lb/nginx-ingress-controller/src/k8s.io/contrib/ingress/controllers/nginx/utils.go:64 +0x55
created by main.(*loadBalancerController).Run
               /home/itsma/service-lb/nginx-ingress-controller/src/k8s.io/contrib/ingress/controllers/nginx/controller.go:1231 +0x1b6
```
@aledbf , the crash happens at the line 746 of controller.go in your commit [761ab92c081fc64a4f78](https://github.com/kubernetes/contrib/commit/761ab92c081fc64a4f789c424ad63723f6d0c2b0) Add support for default backend in Ingress rule.  It seems that at least one of ing.GetNamespace(), ing.Spec.Backend.ServiceName, ing.Spec.Backend.ServicePort is null so that the crash happends. But I check the ingress yaml in our env, they are all set already.

Thanks
Liu Peng

**Comment by bprashanth** [comment]
Did you deploy a default backend per: https://github.com/kubernetes/contrib/tree/master/ingress/controllers/nginx#deployment? which image version are you running?

**Comment by tjliupeng** [comment]
@bprashanth , I don't create the default backend. But in the nginx ingress yaml, we pass the parameter "--default-backend-service=kube-system/mng-portal" to the controller. As to the image, we just down load the contrib master branch and build the image because we need the code change for [pr1711](https://github.com/kubernetes/contrib/pull/1711).

**Comment by thomasjungblut** [comment]
I just encountered this by not supplying a HTTP.Path on the ingress definition, concerning this line

https://github.com/kubernetes/ingress/blob/nginx-0.9.0-beta.11/core/pkg/ingress/controller/controller.go#L813

Any plans to make this whole thing a little more NIL-safe?
