### ISSUE TITLE
[nginx-ingress-controller] crash: fatal error: concurrent map writes

### ISSUE THREAD

**Issue by r0bj** [kubernetes/contrib#2331]
OS: ubuntu 14.04
kubernetes: 1.5.2
docker: 1.12.6

I'm using nginx-ingress-controller as a UDP load balancer in kubernetes pod:
https://gist.github.com/r0bj/ada7be55dd65d2b2376396c42107ba0d

config map:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: udp-lb-config
  namespace: kube-system
data:
  514: "logs-ingress/logs-ingress:514"
```

nginx config:
https://gist.github.com/r0bj/cf0f590d2601443cd4bddbe4812dbe90

nginx-ingress-controller frequently (in my use case more or less once every hour) crash with error message:
```
fatal error: concurrent map writes

goroutine 950 [running]:
runtime.throw(0x1b3d330, 0x15)
	/usr/local/go/src/runtime/panic.go:547 +0x90 fp=0xc820226ab0 sp=0xc820226a98
runtime.mapassign1(0x148a4a0, 0xc8204ef110, 0xc820226bf8, 0xc820226c48)
	/usr/local/go/src/runtime/hashmap.go:445 +0xb1 fp=0xc820226b58 sp=0xc820226ab0
k8s.io/contrib/ingress/vendor/k8s.io/kubernetes/pkg/client/cache.(*DeltaFIFO).queueActionLocked(0xc8200bb340, 0x1a3e8c8, 0x4, 0x19de680, 0xc8203da000, 0x0, 0x0)
	/usr/local/google/home/beeps/goproj/src/k8s.io/contrib/ingress/vendor/k8s.io/kubernetes/pkg/client/cache/delta_fifo.go:320 +0x5d1 fp=0xc820226cc0 sp=0xc820226b58
k8s.io/contrib/ingress/vendor/k8s.io/kubernetes/pkg/client/cache.(*DeltaFIFO).Resync(0xc8200bb340, 0x0, 0x0)
	/usr/local/google/home/beeps/goproj/src/k8s.io/contrib/ingress/vendor/k8s.io/kubernetes/pkg/client/cache/delta_fifo.go:511 +0x4f7 fp=0xc820226e38 sp=0xc820226cc0
k8s.io/contrib/ingress/vendor/k8s.io/kubernetes/pkg/client/cache.(*Reflector).ListAndWatch.func1(0xc8203b6060, 0xc8203b17a0, 0xc820264500, 0xc8203b0a20, 0xc8203b60b0)
	/usr/local/google/home/beeps/goproj/src/k8s.io/contrib/ingress/vendor/k8s.io/kubernetes/pkg/client/cache/reflector.go:289 +0x252 fp=0xc820226f88 sp=0xc820226e38
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc820226f90 sp=0xc820226f88
created by k8s.io/contrib/ingress/vendor/k8s.io/kubernetes/pkg/client/cache.(*Reflector).ListAndWatch
	/usr/local/google/home/beeps/goproj/src/k8s.io/contrib/ingress/vendor/k8s.io/kubernetes/pkg/client/cache/reflector.go:296 +0xde3
```

Full error trace:
https://gist.github.com/r0bj/9027096fc1a511719cacb282e124398b

**Comment by aledbf** [comment]
@r0bj this issue was already reported https://github.com/kubernetes/contrib/issues/1790
It is fixed in master branch in the repo https://github.com/kubernetes/ingress.

**Comment by r0bj** [comment]
@aledbf ok, thanks. Any chance for new release?

**Comment by aledbf** [comment]
@r0bj yes, before the end of next week from the indicated repo ^^
