### ISSUE TITLE
keepalived error: cannot find /proc on a kubernetes 1.7.2 GKE cluster

### ISSUE THREAD

**Issue by kerneljack** [kubernetes/contrib#2715]
Hi I'm trying to get keepalived working (using [1]) on a kubernetes 1.7.2 cluster but the pods all enter into a `CrashLoopBackOff` state with the following error:

```
F0810 20:55:48.149657       1 main.go:103] unexpected error: open /proc/sys/net/ipv4/vs/conntrack: no such file or directory
goroutine 1 [running]:
k8s.io/contrib/keepalived-vip/vendor/github.com/golang/glog.stacks(0x1d9fd00, 0xc400000000, 0x7d, 0xd1)
	/usr/local/google/home/beeps/goproj/src/k8s.io/contrib/keepalived-vip/vendor/github.com/golang/glog/glog.go:766 +0xa5
k8s.io/contrib/keepalived-vip/vendor/github.com/golang/glog.(*loggingT).output(0x1d7f800, 0xc400000003, 0xc420067980, 0x1d19f9b, 0x7, 0x67, 0x0)
	/usr/local/google/home/beeps/goproj/src/k8s.io/contrib/keepalived-vip/vendor/github.com/golang/glog/glog.go:717 +0x337
k8s.io/contrib/keepalived-vip/vendor/github.com/golang/glog.(*loggingT).printf(0x1d7f800, 0x3, 0x14ff936, 0x14, 0xc420655e78, 0x1, 0x1)
	/usr/local/google/home/beeps/goproj/src/k8s.io/contrib/keepalived-vip/vendor/github.com/golang/glog/glog.go:655 +0x14c
k8s.io/contrib/keepalived-vip/vendor/github.com/golang/glog.Fatalf(0x14ff936, 0x14, 0xc420655e78, 0x1, 0x1)
	/usr/local/google/home/beeps/goproj/src/k8s.io/contrib/keepalived-vip/vendor/github.com/golang/glog/glog.go:1145 +0x67
main.main()
	/usr/local/google/home/beeps/goproj/src/k8s.io/contrib/keepalived-vip/main.go:103 +0x5a2
```

Do I need to mount /proc into the containers?

[1] - https://github.com/kubernetes/contrib/tree/master/keepalived-vip

**Comment by kerneljack** [comment]
Anyone have an idea about this? This is on a default, GKE 1.7.2 cluster.

**Comment by jie8357IOII** [comment]
Because k8s node machine lack of 'conntrack' modules, the keepalived-vip pod 'changeSysctl' method raise an error.

Modify default k8s node image to install 'conntrack' may fix the problem, or simply upgrade the whole k8s cluster version (1.10.4-gke.0 version work!).
