### ISSUE TITLE
Zookeeper Statefulset is not working with Kubernetes 1.6

### ISSUE THREAD

**Issue by sgarap** [kubernetes/contrib#2737]
Hi,

Zookeeper statefulsets deployment (with 5 replicas) is not working on Kubernetes 1.6. It is working fine with Kubernetes 1.5.
In Kubernetes 1.6, A Zookeeper pod is unable to connect to other zookeeper pod because of DNS Resolution issue.  

```
2017-08-30 14:18:04,876 [myid:1] - WARN  [WorkerSender[myid=1]:QuorumCnxManager@588] - Cannot open channel to 2 at election address zk-1.zk-headless.default.svc.cluster.local:3888
java.net.UnknownHostException: zk-1.zk-headless.default.svc.cluster.local
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at org.apache.zookeeper.server.quorum.QuorumCnxManager.connectOne(QuorumCnxManager.java:562)
        at org.apache.zookeeper.server.quorum.QuorumCnxManager.toSend(QuorumCnxManager.java:538)
        at org.apache.zookeeper.server.quorum.FastLeaderElection$Messenger$WorkerSender.process(FastLeaderElection.java:452)
        at org.apache.zookeeper.server.quorum.FastLeaderElection$Messenger$WorkerSender.run(FastLeaderElection.java:433)
        at java.lang.Thread.run(Thread.java:745)
2017-08-30 14:18:04,898 [myid:1] - WARN  [WorkerSender[myid=1]:QuorumPeer$QuorumServer@173] - Failed to resolve address: zk-1.zk-headless.default.svc.cluster.local
java.net.UnknownHostException: zk-1.zk-headless.default.svc.cluster.local: Name or service not known
        at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
        at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
        at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
        at java.net.InetAddress.getAllByName0(InetAddress.java:1276)
        at java.net.InetAddress.getAllByName(InetAddress.java:1192)
        at java.net.InetAddress.getAllByName(InetAddress.java:1126)
        at java.net.InetAddress.getByName(InetAddress.java:1076)
        at org.apache.zookeeper.server.quorum.QuorumPeer$QuorumServer.recreateSocketAddresses(QuorumPeer.java:166)
        at org.apache.zookeeper.server.quorum.QuorumCnxManager.connectOne(QuorumCnxManager.java:595)
        at org.apache.zookeeper.server.quorum.QuorumCnxManager.toSend(QuorumCnxManager.java:538)
        at org.apache.zookeeper.server.quorum.FastLeaderElection$Messenger$WorkerSender.process(FastLeaderElection.java:452)
        at org.apache.zookeeper.server.quorum.FastLeaderElection$Messenger$WorkerSender.run(FastLeaderElection.java:433)
        at java.lang.Thread.run(Thread.java:745)

```

In etcd, I noticed that records are created with random generated name.
/ # etcdctl ls /skydns/local/cluster/svc/default/zk-headless
/skydns/local/cluster/svc/default/zk-headless/ccd37d16
/skydns/local/cluster/svc/default/zk-headless/943e6723
/skydns/local/cluster/svc/default/zk-headless/18576dbd
/skydns/local/cluster/svc/default/zk-headless/aa326531
/skydns/local/cluster/svc/default/zk-headless/1ed8054b

[](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/)
This documentation states that, CNAME for SRV Record would be auto-generated-name.my-svc.my-namespace.svc.cluster.local.

Where as in 1.5, it has hostnames as keys.
/ # etcdctl ls /skydns/local/cluster/svc/default/zk-headless
/skydns/local/cluster/svc/default/zk-headless/zk-3
/skydns/local/cluster/svc/default/zk-headless/zk-4
/skydns/local/cluster/svc/default/zk-headless/zk-1
/skydns/local/cluster/svc/default/zk-headless/zk-0
/skydns/local/cluster/svc/default/zk-headless/zk-2

From within the pod curl  zk-1.zk-headless.default.svc.cluster.local:3888 is not working where as using randomnumber from etcd is working. Ex: curl 943e6723.zk-headless.default.svc.cluster.local:3888

As Kube DNS implemenation is changed to save random number in Service Record, can somone please let me know, how to get the zookeeper statefulsets implementation to work on Kubernetes 1.6.

Or Is there any other alternative approach?

Regards,
Sindhura

**Comment by champsaurav** [comment]
Hi,

Are you waiting till all the pods of zk statefulsets come up ?

onnce all the pods comes up it should connect. I am running zookeeper statefulsets on kubernetes 1.6. I get similar logs till all the pods comes up.

Thanks

**Comment by sgarap** [comment]
Hi @champsaurav ,

Yes All the pods are in Running State, and all the pods are complaining about not able to connect to other 4.

**Comment by champsaurav** [comment]
Hi @sgarap,

Can you share your zk config and docker file if possible.

**Comment by sgarap** [comment]
Hi @champsaurav ,
Attached Dockerfile, shell scripts and zookeeper yaml. Please note that I removed the url from where Dockerimage is being pulled, as the URL's are only available in our Intranet. Please note that the same Dockerfile and yaml are working fine in Kubernetes 1.5.

In your Kubernetes 1.6 cluster, how are the SRV Records stored?
Ex: etcdctl ls /skydns/local/cluster/svc/default/zk-headless
[zookeeper.zip](https://github.com/kubernetes/contrib/files/1266154/zookeeper.zip)

**Comment by hieuhc** [comment]
I got exactly the same error. Plus when I deploy kafka version 0.11.0.1, other than 0.10.2.0 as specified in this [description](https://github.com/kubernetes/contrib/blob/master/statefulsets/kafka/Dockerfile), I got this error. It seems like kafka node couldn't talk to each other:

`WARN [Controller-0-to-broker-1-send-thread]: Controller 0's connection to broker kafka-dev-1.kafka-svc-dev.timeseries.svc.cluster.local:9093 (id: 1 rack: null) was unsuccessful (kafka.controller.RequestSendThread)
java.io.IOException: Connection to kafka-dev-1.kafka-svc-dev.timeseries.svc.cluster.local:9093 (id: 1 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:68)
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:264)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:218)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:64)`

**Comment by ManasaMurthy** [comment]
Even I'm facing the same issue. Any update?

**Comment by buyology** [comment]
Seeing this as well, on k8s 1.8:

```bash
[2017-10-04 13:37:53,693] WARN [Controller-0-to-broker-1-send-thread], 
Controller 0's connection to broker kf-1.kf.kafka.svc.cluster.local:9093 (id: 1 rack: null) 
was unsuccessful (kafka.controller.RequestSendThread)
```

Anyone been able to solve this?

**Comment by aitorhh** [comment]
In my case, I solved the problem updating the configuration generated by `zkGenConfig.sh`. As mention in several posts, for example [here](https://stackoverflow.com/questions/30940981/zookeeper-error-cannot-open-channel-to-x-at-election-address) your ip to bind your server (`server.<myid>`) has to be `0.0.0.0`. Therefore the function `print_servers` in the zkGenConfig.sh has to be updated with:

```
function print_servers() {

    for (( i=1; i<=$ZK_REPLICAS; i++ ))
    do
        if [ $i -eq $MY_ID ]; then
            echo "server.$i=0.0.0.0:$ZK_SERVER_PORT:$ZK_ELECTION_PORT"
        else
            echo "server.$i=$NAME-$((i-1)).$DOMAIN:$ZK_SERVER_PORT:$ZK_ELECTION_PORT"
        fi
    done
}
```

**Comment by sgarap** [comment]
Problem was solved by updating kube-dns version.

**Comment by tomplus** [comment]
@sgarap which version of kube-dns do you use ?

**Comment by sgarap** [comment]
1.14.4

**Comment by sibtainabbas10** [comment]
@buyology Were you able to solve this issue? I am having the issue

> Seeing this but for kafka, on k8s 1.8:
> 
> [2017-10-04 13:37:53,693] WARN [Controller-0-to-broker-1-send-thread], 
> Controller 0's connection to broker kf-1.kf.kafka.svc.cluster.local:9093 (id: 1 rack: null) 
> was unsuccessful (kafka.controller.RequestSendThread)
> Anyone been able to solve this?

**Comment by michalswi** [comment]
Similar issue [2722](https://github.com/kubernetes/contrib/issues/2722) already closed but without answer.
