### ISSUE TITLE
Error deploying kafka 0.11.0.1

### ISSUE THREAD

**Issue by hieuhc** [kubernetes/contrib#2772]
I change the version of Kafka to 0.11.0.1 as specified in [statefulsets/kafka](https://github.com/kubernetes/contrib/tree/master/statefulsets/kafka). The first pod pops up and runs fine but it stuck at second pod when the first can not talk to the second one. And because of that the third is not created.

`[2017-09-29 09:28:49,498] WARN [Controller-0-to-broker-1-send-thread]: Controller 0's connection to broker kafka-dev-1.kafka-svc-dev.timeseries.svc.cluster.local:9093 (id: 1 rack: null) was unsuccessful (kafka.controller.RequestSendThread)
java.io.IOException: Connection to kafka-dev-1.kafka-svc-dev.timeseries.svc.cluster.local:9093 (id: 1 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:68)
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:264)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:218)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:64)` 

I tried with Zookeeper 3.4.9 and 3.4.10 (which Kafka 0.11.0.1 is built on) and both yield same result.
Anyone has experienced this? I need this version of Kafka for schema registry server

**Comment by qroussel** [comment]
Hi, I've experencied the exact some problem. (I upgraded to kafka 1.0.0, but the behaviour and the error are the same)
To upgrade I've changed the version with the dockerfile and the option : 
From 
--override inter.broker.protocol.version=0.10.2-IV0
To 
--override inter.broker.protocol.version=1.0-IV0

@hieuhc Have you find a solution or a workaround ?

**Comment by qroussel** [comment]
Hi every one,
The problem comes from the readinessprobe, the command seems to not work correctly and the second podes never get the status ready. 
As a workaround I used a TCP check instead : 

    readinessProbe:
        tcpSocket:
            port: 9093
        initialDelaySeconds: 30
        periodSeconds: 10

It might not be the best way but it works.

**Comment by sibtainabbas10** [comment]
@hieuhc Did you managed to find a solution for this?

**Comment by qroussel** [comment]
@sibtainabbas10  Hi,

Here is the problem I got, and how I fixed it.

I changed the version to 0.11.0.1 (well now even 1.0.0) in  contrib/statefulsets/kafka/Dockerfile
But when I tried to launch the statefulset, it never went up and so was unreachable.
The problem was that in the definition of the stateful they used a shell command that was not compatible with the new version.
So I changed  contrib/statefulsets/kafka/kafka.yaml as described and then it worked fine.

It seems to work fine since, so I didn't change it, nor try another workaround.

**Comment by hieuhc** [comment]
@qroussel: Your solution works for me also. I use kafka 1.0.0 with Zookeeper 3.4. Thanks.
