### ISSUE TITLE
main.go:108] unexpected error: exit status 1

### ISSUE THREAD

**Issue by jstomphorst** [kubernetes/contrib#2818]
Hi guys, 

My pod's are restarting with this error.
Kubernetes v1.9.0
Centos 7

goroutine 1 [running]:
k8s.io/contrib/keepalived-vip/vendor/github.com/golang/glog.stacks(0xc420236e00, 0xc42041a280, 0x4b, 0x9d)
        /usr/local/google/home/mikedanese/go/src/k8s.io/contrib/keepalived-vip/vendor/github.com/golang/glog/glog.go:766 +0xa7
k8s.io/contrib/keepalived-vip/vendor/github.com/golang/glog.(*loggingT).output(0x1e2a9c0, 0xc400000003, 0xc42008e420, 0x1d9086d, 0x7, 0x6c, 0x0)
        /usr/local/google/home/mikedanese/go/src/k8s.io/contrib/keepalived-vip/vendor/github.com/golang/glog/glog.go:717 +0x348
k8s.io/contrib/keepalived-vip/vendor/github.com/golang/glog.(*loggingT).printf(0x1e2a9c0, 0xc400000003, 0x157a081, 0x14, 0xc420527ee8, 0x1, 0x1)
        /usr/local/google/home/mikedanese/go/src/k8s.io/contrib/keepalived-vip/vendor/github.com/golang/glog/glog.go:655 +0x14f
k8s.io/contrib/keepalived-vip/vendor/github.com/golang/glog.Fatalf(0x157a081, 0x14, 0xc420527ee8, 0x1, 0x1)
        /usr/local/google/home/mikedanese/go/src/k8s.io/contrib/keepalived-vip/vendor/github.com/golang/glog/glog.go:1145 +0x67
main.main()
        /usr/local/google/home/mikedanese/go/src/k8s.io/contrib/keepalived-vip/main.go:108 +0x32e

**Comment by jstomphorst** [comment]
Also I am using calico as network provider.

**Comment by fernandohackbart** [comment]
Hello, I have the same issue with Centos 7 and Kubernetes v1.9.0 but using flannel...

**Comment by fernandohackbart** [comment]
In my case I can see `Jan  5 11:57:23 k8s-node1 journal: F0105 11:57:23.407823       1 main.go:98] unexpected error: exit status 1`, looking into the [main.go](https://github.com/kubernetes/contrib/blob/d18731eff4cc109a2754023b8740e47fdb1a783d/keepalived-vip/main.go#L98) seems that `namespace, specified, err := clientConfig.Namespace()` gotten from `clientConfig := kubectl_util.DefaultClientConfig(flags)` is returning `exit status 1`...

**Comment by fernandohackbart** [comment]
Found the issue:  missing ip_vs kernel module in the node that runs the keepalive-vip POD ...

In a running system: `modprobe ip_vs`

Permanent loading the module:
```
cat > /etc/modules-load.d/ip_vs.conf <<EOF
ip_vs
EOF
```

**Comment by fernandohackbart** [comment]
@jstomphorst may you try to check in your installation?

**Comment by jstomphorst** [comment]
I am goint to try it today.. tnx @fernandohackbart

**Comment by jstomphorst** [comment]
jhee!!  It is working.. the pods are not crashing any more..

**Comment by ArcticSnowman** [comment]
I can confirm the same issue and fix for Centos7 with Calico networking.

**Comment by alogoc** [comment]
Same issue here, module must be loaded manually on Centos 7, confirm it works.
