### ISSUE TITLE
travis test is broken.

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes/contrib#2837]
```
$ hack/for-go-proj.sh test
testing hack/../service-loadbalancer/
godep: WARNING: Godep workspaces (./Godeps/_workspace) are deprecated and support for them will be removed when go1.8 is released.
godep: WARNING: Go version (go1.9) & $GO15VENDOREXPERIMENT= wants to enable the vendor experiment, but disabling because a Godep workspace (Godeps/_workspace) exists
ok  	k8s.io/contrib/service-loadbalancer	0.352s
testing hack/../apparmor/loader/
?   	k8s.io/contrib/apparmor/loader	[no test files]
testing hack/../perfdash/
godep: WARNING: Godep workspaces (./Godeps/_workspace) are deprecated and support for them will be removed when go1.8 is released.
godep: WARNING: Go version (go1.9) & $GO15VENDOREXPERIMENT= wants to enable the vendor experiment, but disabling because a Godep workspace (Godeps/_workspace) exists
Fetching prow config from GitHub...
panic: reflect: reflect.Value.Set using unaddressable value
goroutine 1 [running]:
reflect.flag.mustBeAssignable(0x96)
	/home/travis/.gimme/versions/go1.9.linux.amd64/src/reflect/value.go:228 +0x17d
reflect.Value.Set(0x79afe0, 0xc4209ac100, 0x96, 0x79afe0, 0xc420ad1bc8, 0x16)
	/home/travis/.gimme/versions/go1.9.linux.amd64/src/reflect/value.go:1345 +0x2f
github.com/ghodss/yaml.indirect(0x79afe0, 0xc4209ac100, 0x96, 0x0, 0x0, 0x0, 0x0, 0xa43440, 0x80ed80, 0x0, ...)
	/home/travis/gopath/src/k8s.io/contrib/perfdash/Godeps/_workspace/src/github.com/ghodss/yaml/fields.go:48 +0x368
github.com/ghodss/yaml.convertToJSONableObject(0x7b03a0, 0xa42781, 0xc420ede7c0, 0x0, 0x79afe0, 0xc4209ac100, 0x96)
	/home/travis/gopath/src/k8s.io/contrib/perfdash/Godeps/_workspace/src/github.com/ghodss/yaml/yaml.go:106 +0x12b2
github.com/ghodss/yaml.convertToJSONableObject(0x7d3d00, 0xc4201583f0, 0xc420ee6d80, 0xc4209ac100, 0x99, 0x0, 0x0)
	/home/travis/gopath/src/k8s.io/contrib/perfdash/Godeps/_workspace/src/github.com/ghodss/yaml/yaml.go:195 +0xb1b
github.com/ghodss/yaml.convertToJSONableObject(0x7d3d00, 0xc4201583c0, 0xc420ee6ff8, 0x3, 0x7d5320, 0xc420971ff8, 0x95)
	/home/travis/gopath/src/k8s.io/contrib/perfdash/Godeps/_workspace/src/github.com/ghodss/yaml/yaml.go:205 +0x713
github.com/ghodss/yaml.convertToJSONableObject(0x7d3d00, 0xc420158390, 0xc420ee7270, 0xc420971fc0, 0x99, 0x0, 0x0)
	/home/travis/gopath/src/k8s.io/contrib/perfdash/Godeps/_workspace/src/github.com/ghodss/yaml/yaml.go:195 +0xb1b
github.com/ghodss/yaml.convertToJSONableObject(0x7d3d00, 0xc420158360, 0xc420ee74e8, 0x4, 0x7d52c0, 0xc420092608, 0x195)
	/home/travis/gopath/src/k8s.io/contrib/perfdash/Godeps/_workspace/src/github.com/ghodss/yaml/yaml.go:205 +0x713
github.com/ghodss/yaml.convertToJSONableObject(0x7d3d00, 0xc420158330, 0xc420ee7760, 0x7, 0x815bc0, 0xc4200925c8, 0x199)
	/home/travis/gopath/src/k8s.io/contrib/perfdash/Godeps/_workspace/src/github.com/ghodss/yaml/yaml.go:195 +0xb1b
github.com/ghodss/yaml.convertToJSONableObject(0x7d3d00, 0xc420158000, 0xc420ee79d8, 0x79f220, 0xc4201e1090, 0x0, 0x0)
	/home/travis/gopath/src/k8s.io/contrib/perfdash/Godeps/_workspace/src/github.com/ghodss/yaml/yaml.go:195 +0xb1b
github.com/ghodss/yaml.yamlToJSON(0xc4204ce000, 0xbe1e1, 0xbe3e1, 0xc42005bb78, 0x16, 0xc420000180, 0x530e30, 0xc42000e2d0, 0x0)
	/home/travis/gopath/src/k8s.io/contrib/perfdash/Godeps/_workspace/src/github.com/ghodss/yaml/yaml.go:89 +0xa5
github.com/ghodss/yaml.Unmarshal(0xc4204ce000, 0xbe1e1, 0xbe3e1, 0x80bcc0, 0xc420092480, 0x0, 0x0)
	/home/travis/gopath/src/k8s.io/contrib/perfdash/Godeps/_workspace/src/github.com/ghodss/yaml/yaml.go:32 +0xa0
k8s.io/test-infra/prow/config.Load(0xc42001f760, 0x19, 0x7ff9ae1e8408, 0xc420221f00, 0xbe1e1)
	/home/travis/gopath/src/k8s.io/contrib/perfdash/Godeps/_workspace/src/k8s.io/test-infra/prow/config/config.go:190 +0x1ea
k8s.io/contrib/perfdash.getProwConfig(0x0, 0x0, 0x0)
	/home/travis/gopath/src/k8s.io/contrib/perfdash/config.go:125 +0x404
k8s.io/contrib/perfdash.getProwConfigOrDie(0x7d5200)
	/home/travis/gopath/src/k8s.io/contrib/perfdash/config.go:102 +0x22
k8s.io/contrib/perfdash.init()
	/home/travis/gopath/src/k8s.io/contrib/perfdash/config.go:98 +0x698
main.init()
	<autogenerated>:1 +0x53
FAIL	k8s.io/contrib/perfdash	0.283s
godep: go exit status 1
```

This even happens to an empty PR. https://github.com/kubernetes/contrib/pull/2836

**Comment by Random-Liu** [comment]
@kubernetes/sig-scalability-bugs

**Comment by porridge** [comment]
This is because of https://github.com/kubernetes/contrib/issues/2840
