### ISSUE TITLE
perfdash broken by incompatible prow config

### ISSUE THREAD

**Issue by porridge** [kubernetes/contrib#2840]
@bsalamat noticed perfdash is down.
Indeed:

```
porridge@kielonek:~$ kubectl get pods --show-labels|grep perf
perfdash-958854004-5lrbg                   0/1       CrashLoopBackOff   1209       15d       app=perfdash,pod-template-hash=958854004
porridge@kielonek:~$ kubectl logs perfdash-958854004-5lrbg
Fetching prow config from GitHub...
panic: reflect: reflect.Value.Set using unaddressable value

goroutine 1 [running]:
reflect.flag.mustBeAssignable(0x96)
        /usr/local/google/home/porridge/.gvm/gos/go1.9.2/src/reflect/value.go:228 +0x17d
reflect.Value.Set(0x7b4fc0, 0xc420e9f480, 0x96, 0x7b4fc0, 0xc420432c40, 0x16)
        /usr/local/google/home/porridge/.gvm/gos/go1.9.2/src/reflect/value.go:1351 +0x2f
github.com/ghodss/yaml.indirect(0x7b4fc0, 0xc420e9f480, 0x96, 0x0, 0x0, 0x0, 0x0, 0xa6fd60, 0x82bc60, 0x0, ...)
        /usr/local/google/home/porridge/projects/go/src/k8s.io/contrib/perfdash/Godeps/_workspace/src/github.com/ghodss/yaml/fields.go:48 +0x368
github.com/ghodss/yaml.convertToJSONableObject(0x7ca540, 0xa6efa1, 0xc420ff68a0, 0x0, 0x7b4fc0, 0xc420e9f480, 0x96)
        /usr/local/google/home/porridge/projects/go/src/k8s.io/contrib/perfdash/Godeps/_workspace/src/github.com/ghodss/yaml/yaml.go:106 +0x12b2
github.com/ghodss/yaml.convertToJSONableObject(0x7ee580, 0xc420174450, 0xc421000d90, 0xc420e9f480, 0x99, 0x0, 0x0)
        /usr/local/google/home/porridge/projects/go/src/k8s.io/contrib/perfdash/Godeps/_workspace/src/github.com/ghodss/yaml/yaml.go:195 +0xb1b
github.com/ghodss/yaml.convertToJSONableObject(0x7ee580, 0xc420174420, 0xc421001008, 0x3, 0x7efae0, 0xc420e9f478, 0x95)
        /usr/local/google/home/porridge/projects/go/src/k8s.io/contrib/perfdash/Godeps/_workspace/src/github.com/ghodss/yaml/yaml.go:205 +0x713
github.com/ghodss/yaml.convertToJSONableObject(0x7ee580, 0xc4201743f0, 0xc421001280, 0xc420e9f440, 0x99, 0x0, 0x0)
        /usr/local/google/home/porridge/projects/go/src/k8s.io/contrib/perfdash/Godeps/_workspace/src/github.com/ghodss/yaml/yaml.go:195 +0xb1b
github.com/ghodss/yaml.convertToJSONableObject(0x7ee580, 0xc4201743c0, 0xc4210014f8, 0x4, 0x7efa80, 0xc420086848, 0x195)
        /usr/local/google/home/porridge/projects/go/src/k8s.io/contrib/perfdash/Godeps/_workspace/src/github.com/ghodss/yaml/yaml.go:205 +0x713
github.com/ghodss/yaml.convertToJSONableObject(0x7ee580, 0xc420174390, 0xc421001770, 0x7, 0x832920, 0xc420086808, 0x199)
        /usr/local/google/home/porridge/projects/go/src/k8s.io/contrib/perfdash/Godeps/_workspace/src/github.com/ghodss/yaml/yaml.go:195 +0xb1b
github.com/ghodss/yaml.convertToJSONableObject(0x7ee580, 0xc420174000, 0xc4210019e8, 0x7b9480, 0xc420045720, 0x0, 0x0)
        /usr/local/google/home/porridge/projects/go/src/k8s.io/contrib/perfdash/Godeps/_workspace/src/github.com/ghodss/yaml/yaml.go:195 +0xb1b
github.com/ghodss/yaml.yamlToJSON(0xc4204f6000, 0xbf9c2, 0xbfbc2, 0xc42003bb88, 0x16, 0x0, 0x4dfab0, 0xc42006c080, 0x0)
        /usr/local/google/home/porridge/projects/go/src/k8s.io/contrib/perfdash/Godeps/_workspace/src/github.com/ghodss/yaml/yaml.go:89 +0xa5
github.com/ghodss/yaml.Unmarshal(0xc4204f6000, 0xbf9c2, 0xbfbc2, 0x8287e0, 0xc4200866c0, 0x0, 0x0)
        /usr/local/google/home/porridge/projects/go/src/k8s.io/contrib/perfdash/Godeps/_workspace/src/github.com/ghodss/yaml/yaml.go:32 +0xa0
k8s.io/test-infra/prow/config.Load(0xc420016de0, 0x19, 0x7f845fc5ed20, 0xc420475fa0, 0xbf9c2)
        /usr/local/google/home/porridge/projects/go/src/k8s.io/contrib/perfdash/Godeps/_workspace/src/k8s.io/test-infra/prow/config/config.go:190 +0x1ea
main.getProwConfig(0x0, 0x0, 0x0)
        /usr/local/google/home/porridge/projects/go/src/k8s.io/contrib/perfdash/config.go:125 +0x404
main.getProwConfigOrDie(0x7efc00)
        /usr/local/google/home/porridge/projects/go/src/k8s.io/contrib/perfdash/config.go:102 +0x22
main.init()
        /usr/local/google/home/porridge/projects/go/src/k8s.io/contrib/perfdash/config.go:98 +0x693
porridge@kielonek:~$ 
```

I guess that the config in github got out of sync with the vendored `k8s.io/test-infra/prow/config/config.go`. I didn't expect the config to change in an incompatible way when I did https://github.com/kubernetes/contrib/issues/2812
@krzyzacy @BenTheElder @kubernetes/sig-testing-misc how do we prevent this from happening in the future?

**Comment by porridge** [comment]
Actually `godep update ./...` in `perfdash` does not help, still crashes in the same way.
I'll try bisecting the config to see which change broke it.

**Comment by porridge** [comment]
It was broken by https://github.com/kubernetes/test-infra/commit/261a7222d9ae75c40cfe6a3b2d042f22eeca7aab

**Comment by BenTheElder** [comment]
Ah, it should be fine after an update to `ghodss/yaml`. test-infra was on an ancient version, there are some fixes upstream that we're using now.

**Comment by porridge** [comment]
perfdash does not use ghodss/yaml directly

**Comment by porridge** [comment]
unfortunately updating the vendored test-infra causes a different problem, apparently glog is vendoring-hostile:
```/tmp/go-build980103908/k8s.io/contrib/perfdash/_test/perfdash.test flag redefined: log_dir
panic: /tmp/go-build980103908/k8s.io/contrib/perfdash/_test/perfdash.test flag redefined: log_dir

goroutine 1 [running]:
flag.(*FlagSet).Var(0xc420076060, 0xf882e0, 0xc420010c70, 0xbbb9ff, 0x7, 0xbd6ed7, 0x2f)
        /usr/local/google/home/porridge/.gvm/gos/go1.9.2/src/flag/flag.go:793 +0x5e1
flag.(*FlagSet).StringVar(0xc420076060, 0xc420010c70, 0xbbb9ff, 0x7, 0x0, 0x0, 0xbd6ed7, 0x2f)
        /usr/local/google/home/porridge/.gvm/gos/go1.9.2/src/flag/flag.go:696 +0x8b
flag.(*FlagSet).String(0xc420076060, 0xbbb9ff, 0x7, 0x0, 0x0, 0xbd6ed7, 0x2f, 0x222a2529e9d89051)
        /usr/local/google/home/porridge/.gvm/gos/go1.9.2/src/flag/flag.go:709 +0x8b
flag.String(0xbbb9ff, 0x7, 0x0, 0x0, 0xbd6ed7, 0x2f, 0xc420069ec8)
        /usr/local/google/home/porridge/.gvm/gos/go1.9.2/src/flag/flag.go:716 +0x69
k8s.io/test-infra/vendor/github.com/golang/glog.init()
        /usr/local/google/home/porridge/projects/go/src/k8s.io/test-infra/vendor/github.com/golang/glog/glog_file.go:41 +0x14a
k8s.io/test-infra/vendor/k8s.io/apimachinery/pkg/labels.init()
        <autogenerated>:1 +0x64
k8s.io/test-infra/prow/config.init()
        <autogenerated>:1 +0x75
k8s.io/contrib/perfdash.init()
        <autogenerated>:1 +0x6a
main.init()
        <autogenerated>:1 +0x53
FAIL    k8s.io/contrib/perfdash 0.093s
```

**Comment by porridge** [comment]
FWIW, http://perf-dash.k8s.io/ is back up now.
