### ISSUE TITLE
Crash if an reviewer isn't found

### ISSUE THREAD

**Issue by brendandburns** [kubernetes/contrib#46]
``` console
E0901 16:56:30.766474      98 blunderbuss.go:99] No owners found for PR 13025
panic: runtime error: invalid memory address or nil pointer dereference

k8s.io/contrib/mungegithub/pulls.(*BlunderbussMunger).MungePullRequest(0x4c208042130, 0x4c2080362c0, 0x8c15f0, 0xa, 0x8c15f0, 0xa, 0x4c208d05458, 0x4c2098454a0, 0x4c2082c0d00, 0x1, ...)
    /usr/local/google/home/bburns/brendandburns/src/k8s.io/contrib/mungegithub/pulls/blunderbuss.go:85 +0x129
k8s.io/contrib/mungegithub/pulls.mungePullRequestList(0x4c208d02000, 0x64, 0x8d, 0x4c2080362c0, 0x8c15f0, 0xa, 0x8c15f0, 0xa, 0x4c2080ced50, 0x3, ...)
    /usr/local/google/home/bburns/brendandburns/src/k8s.io/contrib/mungegithub/pulls/pulls.go:120 +0x6b4
k8s.io/contrib/mungegithub/pulls.MungePullRequests(0x4c2080362c0, 0x7ffe6e7e8def, 0x24, 0x8c15f0, 0xa, 0x8c15f0, 0xa, 0x0, 0x0, 0x0, ...)
    /usr/local/google/home/bburns/brendandburns/src/k8s.io/contrib/mungegithub/pulls/pulls.go:84 +0x3c6
main.main()
    /usr/local/google/home/bburns/brendandburns/src/k8s.io/contrib/mungegithub/mungegithub.go:68 +0x521

goroutine 5 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0xadb780)
    /usr/local/google/home/bburns/brendandburns/src/k8s.io/contrib/Godeps/_workspace/src/github.com/golang/glog/glog.go:879 +0x78
created by github.com/golang/glog.init·1
    /usr/local/google/home/bburns/brendandburns/src/k8s.io/contrib/Godeps/_workspace/src/github.com/golang/glog/glog.go:410 +0x2a7

goroutine 17 [runnable]:
net/http.(*persistConn).readLoop(0x4c208036370)
    /usr/lib/google-golang/src/net/http/transport.go:928 +0x9ce
created by net/http.(*Transport).dialConn
    /usr/lib/google-golang/src/net/http/transport.go:660 +0xc9f
```

**Comment by eparis** [comment]
do you know what version of code this was?  line 85 is before the glog in question, so I don't understand the trace...

**Comment by eparis** [comment]
I've now hit something similar 4 times. It says it is this line:

```
        if issue.Assignee != nil {
```

But issue being nil just seems impossible to me.  Suddenly my local stuff stopped crashing  :-(

**Comment by foxish** [comment]
This seems like an old GitHub API glitch. Hasn't recurred to my knowledge. Closing.
