### ISSUE TITLE
[Ansible] v2.0.1.0 Does Not Work For CoreOS Deployments

### ISSUE THREAD

**Issue by danehans** [kubernetes/contrib#719]
Ansible 2.0.1.0 (default for Mac OSX 10.10.5) does not work for CoreOS deployments.

```
# ansible --version
ansible 2.0.1.0
  config file = 
  configured module search path = Default w/o overrides
```

Run setup

```
# ./setup.sh 
[DEPRECATION WARNING]: Instead of sudo/sudo_user, use become/become_user and make sure become_method is 'sudo' (default). This feature will be removed 
in a future release. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.

# ./setup.sh 
[DEPRECATION WARNING]: Instead of sudo/sudo_user, use become/become_user and make sure become_method is 'sudo' (default). This feature will be removed 
in a future release. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.

PLAY ***************************************************************************

TASK [pre-ansible : Get os_version from /etc/os-release] ***********************
ok: [core-master]

TASK [pre-ansible : Get distro name from /etc/os-release] **********************
ok: [core-master]

TASK [pre-ansible : Init the is_coreos fact] ***********************************
ok: [core-master]

TASK [pre-ansible : Set the is_coreos fact] ************************************
ok: [core-master]

TASK [pre-ansible : include] ***************************************************
included: /root/contrib/ansible/roles/pre-ansible/tasks/coreos.yml for core-master

TASK [pre-ansible : CoreOS | Check if bootstrap is needed] *********************
fatal: [core-master]: FAILED! => {"changed": false, "failed": true, "rc": 1, "stderr": "", "stdout": "stat: cannot stat '/opt/bin/.bootstrapped': No such file or directory\r\n", "stdout_lines": ["stat: cannot stat '/opt/bin/.bootstrapped': No such file or directory"]}
...ignoring

TASK [pre-ansible : CoreOS | Run bootstrap.sh] *********************************
changed: [core-master]

TASK [pre-ansible : Determine if Atomic] ***************************************
ok: [core-master]

TASK [pre-ansible : Set the is_atomic fact] ************************************
skipping: [core-master]

TASK [pre-ansible : include] ***************************************************
skipping: [core-master]

PLAY ***************************************************************************

TASK [setup] *******************************************************************
fatal: [core-master]: FAILED! => {"changed": false, "failed": true, "module_stderr": "", "module_stdout": "/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)\r\n/opt/bin/pypy/bin/pypy: /lib64/libssl.so.1.0.0: no version information available (required by /opt/bin/pypy/bin/pypy)\r\n/opt/bin/pypy/bin/pypy: /lib64/libcrypto.so.1.0.0: no version information available (required by /opt/bin/pypy/bin/pypy)\r\n/bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)\r\n/bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)\r\nTraceback (most recent call last):\r\n  File \"app_main.py\", line 75, in run_toplevel\r\n  File \"/home/core/.ansible/tmp/ansible-tmp-1459264218.19-221406660048084/setup\", line 5183, in <module>\r\n    main()\r\n  File \"/home/core/.ansible/tmp/ansible-tmp-1459264218.19-221406660048084/setup\", line 139, in main\r\n    data = run_setup(module)\r\n  File \"/home/core/.ansible/tmp/ansible-tmp-1459264218.19-221406660048084/setup\", line 83, in run_setup\r\n    facts = ansible_facts(module)\r\n  File \"/home/core/.ansible/tmp/ansible-tmp-1459264218.19-221406660048084/setup\", line 5118, in ansible_facts\r\n    facts.update(Facts().populate())\r\n  File \"/home/core/.ansible/tmp/ansible-tmp-1459264218.19-221406660048084/setup\", line 2258, in __init__\r\n    self.get_platform_facts()\r\n  File \"/home/core/.ansible/tmp/ansible-tmp-1459264218.19-221406660048084/setup\", line 2304, in get_platform_facts\r\n    self.get_distribution_facts()\r\n  File \"/home/core/.ansible/tmp/ansible-tmp-1459264218.19-221406660048084/setup\", line 2607, in get_distribution_facts\r\n    release = re.search(\"^GROUP=(.*)\", data)\r\n  File \"/opt/bin/pypy/lib-python/2.7/re.py\", line 142, in search\r\n    return _compile(pattern, flags).search(string)\r\nTypeError: expected a readable buffer object\r\n", "msg": "MODULE FAILURE", "parsed": false}

NO MORE HOSTS LEFT *************************************************************
    to retry, use: --limit @cluster.retry

PLAY RECAP *********************************************************************
core-master                : ok=8    changed=1    unreachable=0    failed=1  
```

Traceback

```
Traceback (most recent call last):
  File "app_main.py", line 75, in run_toplevel
  File "/home/core/.ansible/tmp/ansible-tmp-1459264218.19-221406660048084/setup", line 5183, in <module>
    main()
  File "/home/core/.ansible/tmp/ansible-tmp-1459264218.19-221406660048084/setup", line 139, in main
    data = run_setup(module)
  File "/home/core/.ansible/tmp/ansible-tmp-1459264218.19-221406660048084/setup", line 83, in run_setup
    facts = ansible_facts(module)
  File "/home/core/.ansible/tmp/ansible-tmp-1459264218.19-221406660048084/setup", line 5118, in ansible_facts
    facts.update(Facts().populate())
  File "/home/core/.ansible/tmp/ansible-tmp-1459264218.19-221406660048084/setup", line 2258, in __init__
    self.get_platform_facts()
  File "/home/core/.ansible/tmp/ansible-tmp-1459264218.19-221406660048084/setup", line 2304, in get_platform_facts
    self.get_distribution_facts()
  File "/home/core/.ansible/tmp/ansible-tmp-1459264218.19-221406660048084/setup", line 2607, in get_distribution_facts
    release = re.search("^GROUP=(.*)", data)
  File "/opt/bin/pypy/lib-python/2.7/re.py", line 142, in search
    return _compile(pattern, flags).search(string)
TypeError: expected a readable buffer object
```

More information can be found here https://github.com/kubernetes/contrib/pull/655

**Comment by paulmcgoldrick** [comment]
looks like update.conf has moved from `/etc/coreos/update.conf` to 
cat /usr/share/coreos/update.conf ` in 991.2.0 at least.

**Comment by danehans** [comment]
@paulmcgoldrick ^ sounds like a separate issue. This issue is related to the version of ansible to use for the contrib/ansible vagrant environment. Do you mind creating a separate issue?

**Comment by paulmcgoldrick** [comment]
@danehans Not at all, sorry for the noise.
